//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace UI.MyProxy {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebService1Soap", Namespace="http://tempuri.org/")]
    public partial class WebService1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CreateNewCardOperationCompleted;
        
        private System.Threading.SendOrPostCallback allCardTransactionInMonthOperationCompleted;
        
        private System.Threading.SendOrPostCallback allCardTransactionOperationCompleted;
        
        private System.Threading.SendOrPostCallback VerifyDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback PaySomeoneOperationCompleted;
        
        private System.Threading.SendOrPostCallback AllCreditCardsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService1() {
            this.Url = global::UI.Properties.Settings.Default.UI_MyProxy_WebService1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CreateNewCardCompletedEventHandler CreateNewCardCompleted;
        
        /// <remarks/>
        public event allCardTransactionInMonthCompletedEventHandler allCardTransactionInMonthCompleted;
        
        /// <remarks/>
        public event allCardTransactionCompletedEventHandler allCardTransactionCompleted;
        
        /// <remarks/>
        public event VerifyDetailsCompletedEventHandler VerifyDetailsCompleted;
        
        /// <remarks/>
        public event PaySomeoneCompletedEventHandler PaySomeoneCompleted;
        
        /// <remarks/>
        public event AllCreditCardsCompletedEventHandler AllCreditCardsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateNewCard", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CreateNewCard(int ownerID, string ownerFirstName, string ownerLastName) {
            object[] results = this.Invoke("CreateNewCard", new object[] {
                        ownerID,
                        ownerFirstName,
                        ownerLastName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CreateNewCardAsync(int ownerID, string ownerFirstName, string ownerLastName) {
            this.CreateNewCardAsync(ownerID, ownerFirstName, ownerLastName, null);
        }
        
        /// <remarks/>
        public void CreateNewCardAsync(int ownerID, string ownerFirstName, string ownerLastName, object userState) {
            if ((this.CreateNewCardOperationCompleted == null)) {
                this.CreateNewCardOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateNewCardOperationCompleted);
            }
            this.InvokeAsync("CreateNewCard", new object[] {
                        ownerID,
                        ownerFirstName,
                        ownerLastName}, this.CreateNewCardOperationCompleted, userState);
        }
        
        private void OnCreateNewCardOperationCompleted(object arg) {
            if ((this.CreateNewCardCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateNewCardCompleted(this, new CreateNewCardCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/allCardTransactionInMonth", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Transaction[] allCardTransactionInMonth(string cardNumber, int month, int year) {
            object[] results = this.Invoke("allCardTransactionInMonth", new object[] {
                        cardNumber,
                        month,
                        year});
            return ((Transaction[])(results[0]));
        }
        
        /// <remarks/>
        public void allCardTransactionInMonthAsync(string cardNumber, int month, int year) {
            this.allCardTransactionInMonthAsync(cardNumber, month, year, null);
        }
        
        /// <remarks/>
        public void allCardTransactionInMonthAsync(string cardNumber, int month, int year, object userState) {
            if ((this.allCardTransactionInMonthOperationCompleted == null)) {
                this.allCardTransactionInMonthOperationCompleted = new System.Threading.SendOrPostCallback(this.OnallCardTransactionInMonthOperationCompleted);
            }
            this.InvokeAsync("allCardTransactionInMonth", new object[] {
                        cardNumber,
                        month,
                        year}, this.allCardTransactionInMonthOperationCompleted, userState);
        }
        
        private void OnallCardTransactionInMonthOperationCompleted(object arg) {
            if ((this.allCardTransactionInMonthCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.allCardTransactionInMonthCompleted(this, new allCardTransactionInMonthCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/allCardTransaction", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Transaction[] allCardTransaction(string cardNumber) {
            object[] results = this.Invoke("allCardTransaction", new object[] {
                        cardNumber});
            return ((Transaction[])(results[0]));
        }
        
        /// <remarks/>
        public void allCardTransactionAsync(string cardNumber) {
            this.allCardTransactionAsync(cardNumber, null);
        }
        
        /// <remarks/>
        public void allCardTransactionAsync(string cardNumber, object userState) {
            if ((this.allCardTransactionOperationCompleted == null)) {
                this.allCardTransactionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnallCardTransactionOperationCompleted);
            }
            this.InvokeAsync("allCardTransaction", new object[] {
                        cardNumber}, this.allCardTransactionOperationCompleted, userState);
        }
        
        private void OnallCardTransactionOperationCompleted(object arg) {
            if ((this.allCardTransactionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.allCardTransactionCompleted(this, new allCardTransactionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VerifyDetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool VerifyDetails(string cardNumber, int cardCCV, int cardExpirationMonth, int cardExpirationYear) {
            object[] results = this.Invoke("VerifyDetails", new object[] {
                        cardNumber,
                        cardCCV,
                        cardExpirationMonth,
                        cardExpirationYear});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void VerifyDetailsAsync(string cardNumber, int cardCCV, int cardExpirationMonth, int cardExpirationYear) {
            this.VerifyDetailsAsync(cardNumber, cardCCV, cardExpirationMonth, cardExpirationYear, null);
        }
        
        /// <remarks/>
        public void VerifyDetailsAsync(string cardNumber, int cardCCV, int cardExpirationMonth, int cardExpirationYear, object userState) {
            if ((this.VerifyDetailsOperationCompleted == null)) {
                this.VerifyDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerifyDetailsOperationCompleted);
            }
            this.InvokeAsync("VerifyDetails", new object[] {
                        cardNumber,
                        cardCCV,
                        cardExpirationMonth,
                        cardExpirationYear}, this.VerifyDetailsOperationCompleted, userState);
        }
        
        private void OnVerifyDetailsOperationCompleted(object arg) {
            if ((this.VerifyDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerifyDetailsCompleted(this, new VerifyDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PaySomeone", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Transaction PaySomeone(string payingCardNumber, int payingCardCCV, int payingCardExpirationMonth, int payingCardExpirationYear, string recivingCard, double payingHowMuch) {
            object[] results = this.Invoke("PaySomeone", new object[] {
                        payingCardNumber,
                        payingCardCCV,
                        payingCardExpirationMonth,
                        payingCardExpirationYear,
                        recivingCard,
                        payingHowMuch});
            return ((Transaction)(results[0]));
        }
        
        /// <remarks/>
        public void PaySomeoneAsync(string payingCardNumber, int payingCardCCV, int payingCardExpirationMonth, int payingCardExpirationYear, string recivingCard, double payingHowMuch) {
            this.PaySomeoneAsync(payingCardNumber, payingCardCCV, payingCardExpirationMonth, payingCardExpirationYear, recivingCard, payingHowMuch, null);
        }
        
        /// <remarks/>
        public void PaySomeoneAsync(string payingCardNumber, int payingCardCCV, int payingCardExpirationMonth, int payingCardExpirationYear, string recivingCard, double payingHowMuch, object userState) {
            if ((this.PaySomeoneOperationCompleted == null)) {
                this.PaySomeoneOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPaySomeoneOperationCompleted);
            }
            this.InvokeAsync("PaySomeone", new object[] {
                        payingCardNumber,
                        payingCardCCV,
                        payingCardExpirationMonth,
                        payingCardExpirationYear,
                        recivingCard,
                        payingHowMuch}, this.PaySomeoneOperationCompleted, userState);
        }
        
        private void OnPaySomeoneOperationCompleted(object arg) {
            if ((this.PaySomeoneCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PaySomeoneCompleted(this, new PaySomeoneCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AllCreditCards", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CreditCard[] AllCreditCards() {
            object[] results = this.Invoke("AllCreditCards", new object[0]);
            return ((CreditCard[])(results[0]));
        }
        
        /// <remarks/>
        public void AllCreditCardsAsync() {
            this.AllCreditCardsAsync(null);
        }
        
        /// <remarks/>
        public void AllCreditCardsAsync(object userState) {
            if ((this.AllCreditCardsOperationCompleted == null)) {
                this.AllCreditCardsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAllCreditCardsOperationCompleted);
            }
            this.InvokeAsync("AllCreditCards", new object[0], this.AllCreditCardsOperationCompleted, userState);
        }
        
        private void OnAllCreditCardsOperationCompleted(object arg) {
            if ((this.AllCreditCardsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AllCreditCardsCompleted(this, new AllCreditCardsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Transaction {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CreditCard {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CreateNewCardCompletedEventHandler(object sender, CreateNewCardCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateNewCardCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateNewCardCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void allCardTransactionInMonthCompletedEventHandler(object sender, allCardTransactionInMonthCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class allCardTransactionInMonthCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal allCardTransactionInMonthCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Transaction[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Transaction[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void allCardTransactionCompletedEventHandler(object sender, allCardTransactionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class allCardTransactionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal allCardTransactionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Transaction[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Transaction[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void VerifyDetailsCompletedEventHandler(object sender, VerifyDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerifyDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerifyDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void PaySomeoneCompletedEventHandler(object sender, PaySomeoneCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PaySomeoneCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PaySomeoneCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Transaction Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Transaction)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AllCreditCardsCompletedEventHandler(object sender, AllCreditCardsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AllCreditCardsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AllCreditCardsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CreditCard[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CreditCard[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591